version: '2.1'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    restart: unless-stopped

  server:
    build: ./
    container_name: concert-finder
    ports:
      - 5000:5000
    links:
      - mongodb

  client:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    links:
      - server
